version: '3.7'

services:
  db:
    container_name: school-administration-system-mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: school-administration-system
    ports:
      - "33306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d:ro

  external:
    container_name: school-administration-system-external
    build:
      context: ../external
      dockerfile: external-system.Dockerfile
    image: school-administration-system-external:1.0
    environment:
      TZ: Asia/Singapore
      NODE_ENV: production
    ports:
      - "5000:5000"

  phpmyadmin:
    container_name: database-interface
    image: lscr.io/linuxserver/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - db
